# Server settings
server:
  port: 3003
  error:
    include-stacktrace: never

# Spring datasource settings
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:parking}?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin123}
  
# Spring JPA settings  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

# Garage settings
garage:
  url: ${GARAGE_URL:http://localhost:3000/garage}

# SpringDoc settings
springdoc:
  server:
    url: ${SWAGGER_SERVER_URL:http://localhost:${server.port}}
    description: ${SERVER_DESCRIPTION:Development server}